#################################################
# CREATE AVD
#################################################

AVD_CMD=$ANDROID_HOME/tools/bin/avdmanager

# ANDROID_VARIABLES
ANDROID_DEVICE_DIRECTORY=$ANDROID_HOME/devices
ANDROID_SKINS_DIRECTORY=$ANDROID_HOME/skins

# TEST DEVICE VARIABLES
TEST_DEVICE=pixel
TEST_DEVICE_SDK=25

TEST_DEVICE_NAME=${TEST_DEVICE}_${TEST_DEVICE_SDK}
TEST_DEVICE_DIRECTORY=$ANDROID_DEVICE_DIRECTORY/$TEST_DEVICE_NAME
TEST_DEVICE_SKINS_DIRECTORY=$ANDROID_SKINS_DIRECTORY/$TEST_DEVICE

# SKIN VARIABLES
SOURCE_SKINS_DIRECTORY=skins

# AVD CONFIG VARIABLES
CONFIG_TEMPLATE_DIRECTORY=templates
CONFIG_TEMPLATE_PATH=$CONFIG_TEMPLATE_DIRECTORY/$TEST_DEVICE.template

# SEE IF THE AVD HAS ALREADY BEEN CREATED BY THIS SCRIPT
if [ ! -d "$TEST_DEVICE_DIRECTORY" ]; then

  # CREATE THE TEST DEVICE USING THE
  # AVDMANAGER COMMAND.
  echo "creating $TEST_DEVICE_NAME"
  $AVD_CMD create avd \
  --force \
  --name $TEST_DEVICE_NAME \
  --package "system-images;android-$TEST_DEVICE_SDK;google_apis;x86" \
  --tag "google_apis" \
  --device $TEST_DEVICE \
  --path $TEST_DEVICE_DIRECTORY

  # COPY THE PIXEL SKIN INTO THE ANDROID SKIN DIRECTORY IF
  # ANDROID STUDIO HAS NOT ALREADY DOWNLOADED THE PIXEL SKIN
  if [ ! -d "$TEST_DEVICE_SKINS_DIRECTORY" ]; then
    echo "copying $TEST_DEVICE skin"
    cp -r $SOURCE_SKINS_DIRECTORY/ $ANDROID_SKINS_DIRECTORY/
  fi

  # CREATE A TEMPORARY COPY OF THE TEMPLATE FILE
  # SO WE CAN MODIFY IT WITHOUT LOSING THE ORIGINAL
  cp $CONFIG_TEMPLATE_PATH $CONFIG_TEMPLATE_PATH.tmp

  # REPLACE THE MOUSTACHE TAGS WITH THE REQUIRED INFORMATION
  sed -i ".sed" "s|{{skin_name}}|$TEST_DEVICE|" $CONFIG_TEMPLATE_PATH.tmp
  sed -i ".sed" "s|{{skin_path}}|$ANDROID_SKINS_DIRECTORY/$TEST_DEVICE|" $CONFIG_TEMPLATE_PATH.tmp

  # APPEND THE TEMPLATE FILE TO THE END OF THE TEST DEVICE'S CONFIG.INI
  cat $CONFIG_TEMPLATE_PATH.tmp >> $TEST_DEVICE_DIRECTORY/config.ini

  # DELETE THE TEMPORARY TEMPLATE &
  # DELETE THE TEMPORARY SED FILES
  rm $CONFIG_TEMPLATE_PATH.tmp
  rm $CONFIG_TEMPLATE_PATH.tmp.sed

else
  echo "$TEST_DEVICE_NAME already created."
fi
